temp_dir: /opt/autoposter/temp
# Use 'vk' or 'tg'
source: vk # Only VK supported now.
pool_interval: 60
log_level: info
log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
telegram:
  channel_id: 
  token: 
  # https://core.telegram.org/api/obtaining_api_id
  # From https://my.telegram.org/apps
  api_id: 
  api_hash: 
vk:
  token: 
  group_id: 
instagram:
  # https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login/create-a-meta-app-with-instagram#api-setup-with-instagram-login
  app_token: IGAB444gzGnfxBZAE9oemR4SDZASSy13TkluTUdJMk5MdjBZAOXNqaG5ybENqVDZAONDdRdndmdWw4cXpPWWNaZAElBOXRvQnF1eFVyeE41alBFUUNMcU5qQnVCTkJWbXZAtUlJKZAF8xWEJOQjYtZAFRMSVJVN05WajVmRW1iVEk1cHUzOAZDZD
  
  proxy: 
  web_photo_location: https://ap-media.apt-1088.online
  fill_color: "#fff"
  default_tags:
    - your
    - favorite
    - tags 
    - for  
    - every
    - post
  total_tags_count: 16

# https://imagga.com/profile/dashboard
imagga:
  api_key: 
  api_secret: 


replaces:
  id1:
    tg: '[Pavel Durov](https://t.me/durov)'
    inst: '@durov'