server {
    listen 80;
    listen [::]:80;
    server_name %CONTENT_SITE_NAME%;

    root %APP_DIR%/temp/content;
    index index.html;

    location / {
            try_files $uri $uri/ =404;
    }
}
